include:
  - .nojekyll


sass:
    sass_dir: sass

# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9000




encoding:         UTF-8
exclude:          [assets/scss/]

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

# Site vars
#url:    "http://fezvrasta.github.io"
repo:   https://github.com/fezvrasta/bootstrap-material-design
#baseurl: "/bootstrap-material-design"
url: "http://rosskevin.github.io"

# other variables generated in

#blog:             http://blog.getbootstrap.com
#expo:             http://expo.getbootstrap.com
#themes:           http://themes.getbootstrap.com

#
cdn:
#  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://cdn.rawgit.com/fezvrasta/bootstrap-material-design/v4-dev/dist/css/bootstrap-material-design.css
#  css_hash:       "sha384-XXXXXXXX"
  js:             https://cdn.rawgit.com/fezvrasta/bootstrap-material-design/v4-dev/dist/js/bootstrap-material-design.js
#  js_hash:        "sha384-XXXXXXXX"

  # fonts
  font_roboto:    http://fonts.googleapis.com/css?family=Roboto:300,400,500,700
  font_icons:     https://fonts.googleapis.com/icon?family=Material+Icons

  # VERSION is substituted in variables.rb and these are made available as site.data.cdn.*
  jquery:         https://ajax.googleapis.com/ajax/libs/jquery/VERSION/jquery
  bootstrap:      https://cdn.rawgit.com/twbs/bootstrap/VERSION/dist/js/bootstrap
  tether:         https://cdn.rawgit.com/HubSpot/tether/vVERSION/dist/js/tether



#twitter:
#  username: getbootstrap
#
#social:
#  type: organization
#  name: twbs
#  links: ["https://www.facebook.com/getbootstrap/", "https://twitter.com/getbootstrap"]
