app:
    resource: "@AppBundle/Controller/"
    type:     annotation
black_sheep_music_library:
    resource: '@BlackSheepMusicLibraryBundle/Resources/config/routing.yml'
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"



