app:
    resource: "@AppBundle/Controller/"
    type:     annotation
black_sheep_music_libary_api:
    resource: '@BlackSheepMusicLibraryBundle/Controller/ApiController.php'
    type:     rest
    prefix:   /api/
library:
    resource: "@BlackSheepMusicLibraryBundle/Resources/config/routing.yml"
    prefix:   /library/
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"



