services:
    black_sheep_music_library.last_fm.last_fm_artist:
        class: BlackSheep\MusicLibraryBundle\LastFm\LastFmArtist
        arguments: [BlackSheep\MusicLibraryBundle\LastFm\LastFmArtistInfo]