services:
    black_sheep_music_library.song_event_subscriber:
        class: BlackSheep\MusicLibraryBundle\EventListener\SongEventSubscriber
        arguments: ['@black_sheep_music_library.repository.songs_repository']
        tags:
            - { name: kernel.event_subscriber }
    delayed_event_dispatcher:
        class: BlackSheep\MusicLibraryBundle\Dispatcher\DelayedEventDispatcher
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: "kernel.event_subscriber" }
    black_sheep_music_library.services.streamer_service:
        class: BlackSheep\MusicLibraryBundle\Services\StreamerService
        arguments: ["%black_sheep_music_library.ffmpeg_path%", "%black_sheep_music_library.bitrate%"]
    black_sheep.music_library.api_model.api_artist_data:
        class: BlackSheep\MusicLibraryBundle\ApiModel\ApiArtistData
        arguments: ['@router']
    black_sheep.music_library.api_model.api_song_data:
        class: BlackSheep\MusicLibraryBundle\ApiModel\ApiSongData
        arguments: ['@router']
    black_sheep.music_library.api_model.api_album_data:
        class: BlackSheep\MusicLibraryBundle\ApiModel\ApiAlbumData
        arguments: ['@router']